### ISSUE TITLE
X6B bricked

### ISSUE THREAD

**Issue by Bucc1o** [Cleric-K/FlySkyRxFirmwareRssiMod#15]
Hi all i'm new and i need an help.. i tried to flash my x6b with stlink utility, first time i don't get it working but after switching the power form 3.3v to 5v (+vcc pad on the receiver) it worked but the utility say to me "Can not read memory! Disable Read Out Protection and retry"
.. after a research i set on Option Bytes menu, Read Out Protection to Level 0.. now my receiver is bricked i think.. the red led no longer turns on.. on another closed issue here i see another member with the same problem, so i follow the procedure wrote by Clericto connect under reset the board. but it not work properly.. (image attached).
what can i do? 
![screen1](https://user-images.githubusercontent.com/73337875/97013039-d62c7b00-1548-11eb-849a-99b2695cb3b0.jpg)

**Comment by Bucc1o** [comment]
This after i press ok button 
![screen 2](https://user-images.githubusercontent.com/73337875/97013198-11c74500-1549-11eb-8adf-a15fd8dfff9b.jpg)

**Comment by Cleric-K** [comment]
Which of the wires you have connected between the stlink and receiver?

**Comment by Bucc1o** [comment]
![IMG_20201023_210606](https://user-images.githubusercontent.com/73337875/97044032-b3638c00-1573-11eb-8599-f85b018d4bf5.jpg)
I have connected the 3v3, dat, clk and gnd.. the rst connected to other gnd on the st link ( i release it once clicked connect on st link utility)

PS: When it worked before set the read out protection to 0, i have connected the 5v on the vcc pad, dat, clk and gnd.. maybe this info can help

**Comment by Cleric-K** [comment]
It's better to power with 5V from stlink and not use 3.3V otherwise it looks as it should.

**Comment by Bucc1o** [comment]
Sorry i don't understand what you said.. so i have to connect It under reset using 5v from st link, gnd, dat, clk and RST manually releasing it when connect?

**Comment by Bucc1o** [comment]
I've solved the problem.. today i tested with a tester each wire and solder and found one wire broken (the gnd) so i replaced it with a new one and follow your istruction using 5v instead of 3v and it works.. i flashed the firmware successfully.. thank you so much Cleric! You saved my receiver with your instruction ;)

For those who have the same problem, make sure of your wire and solder and if needed use 5v from st link instead of 3v

**Comment by Cleric-K** [comment]
Great! I'm glad you figured it out.
