### ISSUE TITLE
IA8X AND IA8S 

### ISSUE THREAD

**Issue by iggut** [Cleric-K/FlySkyRxFirmwareRssiMod#3]
IA8X AND IA8S are the two receivers included with the FlySky Nirvana. Any way to get fw with RSSI on ch 14 for those 2?

Let me know what I can do to help. I have an stlink and both those rx chips....just lack the knowledge to code

**Comment by Cleric-K** [comment]
Well, I can take a look. If the firmware is similar to the other receivers it shouldn't be hard to adapt the same patching scheme.

I'll need dump from the firmwares. Stlink can do it. You just need to locate the SWCLK and SWDIO pads.
